'use strict';

import fs from 'fs';
import path from 'path';
import { extractFocus, extractOpenQuestions, extractShadowEntries, extractSection } from './concepts';

const MARKER = '<!-- cortex-dev:generated';
const MARKER_HASH = '# cortex-dev:generated';

export interface SyncTarget {
  file: string;
  written: boolean;
  skipped: boolean;
  reason?: string;
}

export interface SyncResult {
  targets: SyncTarget[];
}

export function syncGenome(cwd: string): SyncResult {
  const genomeDir = path.join(cwd, '.genome');
  const ctx = buildCtx(genomeDir);

  return {
    targets: [
      writeTarget(path.join(cwd, 'CLAUDE.md'),       buildClaudeMd(ctx),          MARKER),
      writeTarget(path.join(cwd, '.cursorrules'),     buildCursorRules(ctx),       MARKER_HASH),
      writeTarget(
        path.join(cwd, '.github', 'copilot-instructions.md'),
        buildCopilotInstructions(ctx),
        MARKER,
        path.join(cwd, '.github'),
      ),
    ],
  };
}

// ── content builders ──────────────────────────────────────────────────────────

interface Ctx {
  focus: string;
  invariants: string;
  hardLines: string;
  openQuestions: string[];
  shadowLines: string;
}

function buildCtx(genomeDir: string): Ctx {
  const read = (f: string) => {
    const p = path.join(genomeDir, f);
    return fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : '';
  };

  const genotypeMd  = read('00_GENOTYPE.md');
  const phenotypeMd = read('10_PHENOTYPE.md');
  const shadowMd    = read('40_SHADOW.md');

  const focus = extractFocus(phenotypeMd);

  const invariants = (extractSection(genotypeMd, '§2') || '').trim();
  const hardLines  = (extractSection(genotypeMd, '§4') || '').trim();

  const openQuestions = extractOpenQuestions(phenotypeMd);

  const shadowEntries = extractShadowEntries(shadowMd);
  const shadowLines = shadowEntries.length > 0
    ? shadowEntries.map((e) => `- **${e.title}**${e.constraint ? ': ' + e.constraint : ''}`).join('\n')
    : '(none documented yet)';

  return { focus, invariants, hardLines, openQuestions, shadowLines };
}

function buildClaudeMd(ctx: Ctx): string {
  const questions = ctx.openQuestions.length > 0
    ? ctx.openQuestions.map((q) => `- ${q}`).join('\n')
    : '(none)';

  return `<!-- cortex-dev:generated — edit .genome/ files and run \`cortex sync\` to regenerate -->

# Project Context

## Current focus

${ctx.focus}

## Architecture invariants

${ctx.invariants || '(fill in .genome/00_GENOTYPE.md §2)'}

## Hard lines

${ctx.hardLines || '(fill in .genome/00_GENOTYPE.md §4)'}

## Forbidden approaches — do not propose

${ctx.shadowLines}

## Open questions

${questions}
`;
}

function buildCursorRules(ctx: Ctx): string {
  const questions = ctx.openQuestions.length > 0
    ? ctx.openQuestions.map((q) => `- ${q}`).join('\n')
    : '(none)';

  return `# cortex-dev:generated — edit .genome/ files and run \`cortex sync\` to regenerate

## Current focus

${ctx.focus}

## Architecture rules

${ctx.invariants || '(fill in .genome/00_GENOTYPE.md §2)'}

## Hard lines — do not violate

${ctx.hardLines || '(fill in .genome/00_GENOTYPE.md §4)'}

## Do not propose these approaches

${ctx.shadowLines}

## Open questions

${questions}
`;
}

function buildCopilotInstructions(ctx: Ctx): string {
  return `<!-- cortex-dev:generated — edit .genome/ files and run \`cortex sync\` to regenerate -->

## Current focus

${ctx.focus}

## Architecture invariants

${ctx.invariants || '(fill in .genome/00_GENOTYPE.md §2)'}

## Hard lines

${ctx.hardLines || '(fill in .genome/00_GENOTYPE.md §4)'}

## Rejected approaches — do not propose

${ctx.shadowLines}
`;
}

// ── file writer ───────────────────────────────────────────────────────────────

function writeTarget(
  filePath: string,
  content: string,
  marker: string,
  ensureParent?: string,
): SyncTarget {
  const file = path.relative(process.cwd(), filePath);

  if (fs.existsSync(filePath)) {
    const existing = fs.readFileSync(filePath, 'utf8');
    if (!existing.startsWith(marker)) {
      return { file, written: false, skipped: true, reason: 'file exists and was not generated by cortex — skipping to avoid overwrite' };
    }
  }

  if (ensureParent && !fs.existsSync(ensureParent)) {
    fs.mkdirSync(ensureParent, { recursive: true });
  }

  fs.writeFileSync(filePath, content, 'utf8');
  return { file, written: true, skipped: false };
}
